[versions]
accompanist = "0.34.0"
agp = "8.5.1"
android-sdk-compile = "35"
android-sdk-min = "24"
android-sdk-target = "35"
androidx-core = "1.13.1"
androidx-espresso-core = "3.6.1"
androidx-junit = "1.2.1"
androidx-lifecycle = "2.8.4"
androidx-room = "2.6.1"
compose = "1.6.8"
compose-activity = "1.9.1"
compose-material3 = "1.2.1"
compose-navigation = "2.8.0-beta06"
dagger = "2.51.1"
desugar-jdk-libs = "2.0.4"
google-material = "1.12.0"
gson = "2.11.0"
gson-extras = "1.3.0"
hilt = "1.2.0"
junit = "4.13.2"
kotlin = "2.0.0"
kotlin-ksp = "2.0.0-1.0.24"
kotlinx-coroutines = "1.8.1"
kotlinx-serialization = "1.7.1"
ktor = "2.3.12"
medzik-android-utils = "1.8.0"
medzik-libcrypto = "1.2.0"
migbase64 = "2.2"

[libraries]
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso-core" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
compose-androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }
compose-material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "compose-navigation" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
dagger-hilt = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar-jdk-libs" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
gson-extras = { module = "org.danilopianini:gson-extras", version.ref = "gson-extras" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
medzik-android-compose = { module = "dev.medzik.android:compose", version.ref = "medzik-android-utils" }
medzik-android-crypto = { module = "dev.medzik.android:crypto", version.ref = "medzik-android-utils" }
medzik-android-utils = { module = "dev.medzik.android:utils", version.ref = "medzik-android-utils" }
medzik-libcrypto = { module = "dev.medzik:libcrypto", version.ref = "medzik-libcrypto" }
migbase64 = { module = "com.brsanthu:migbase64", version.ref = "migbase64" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
androidx-room = { id = "androidx.room", version.ref = "androidx-room" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
